### ISSUE TITLE
Change Logo web interface

### ISSUE THREAD

**Issue by trilokmohnani** [Graylog2/graylog2-cookbook#105]
Is there any way to change or customize the web interface logo and login screen.

Thanks in Advance
BR

**Comment by joschi** [comment]
@trilokmohnani No, that's currently not possible without building a custom (unsupported) version of Graylog.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by trilokmohnani** [comment]
Thanks Joschi!!
