### ISSUE TITLE
Graylog ES version

### ISSUE THREAD

**Issue by jamiebuxxx** [Graylog2/graylog2-cookbook#106]
When reading through the README in order to prepare for an upgrade to latest version of Graylog, I noticed following statement:
"You have to use a certain version of Elasticsearch for every Graylog Version, currently this is 5.5.1. "

So, does that mean we will need to update our Elasticsearch cluster as well? We are currently running 2.2.0.

**Comment by mariussturm** [comment]
Hi,
I think you can continue to work with 5.5.1 but you have to switch to the HTTP protocol (see the attributes file of the latest cookbook: `default['graylog2']['elasticsearch']['hosts']`). You can read through the upgrade notes for each version here: http://docs.graylog.org/en/2.4/pages/upgrade.html.
