### ISSUE TITLE
Importing configuration using mongorestore for initial provisioning

### ISSUE THREAD

**Issue by henrikjohansen** [Graylog2/graylog2-cookbook#12]
In order to recreate / provision a fully functioning Graylog cluster we would need to have access to most if not all of the REST resources using LWRPs or similar - that's a lot of work to create, maintain, test, etc.

Since the configuration is persisted in mongo it might be a good idea to support restoring the entire configuration from a mongodump - something along the lines of this:

file 'mongorestore_lockfile' do
  action :create_if_missing
  notifies :run, 'execute[run_mongorestore]', :immediately
end

execute 'run_mongorestore' do
  command 'mongorestore -foo - bar ...'
  action :nothing
end

I might do a PR if your interested in having such a feature ?

**Comment by mariussturm** [comment]
Hi Henrik,
thanks for this idea! But at the moment I would like to go with your other idea https://github.com/Graylog2/graylog2-cookbook/issues/11 Yes it is a lot of work but we could reuse the it in other projects like the Puppet manifest as well. The idea is to extract a ruby gem with all REST resources to make it easy for people to build something against the GL api.
