### ISSUE TITLE
Permissions for config files too open

### ISSUE THREAD

**Issue by gregkare** [Graylog2/graylog2-cookbook#13]
I've just realised that the permissions for the config files are all set to 0644. The server config file for example includes things like clear text SMTP credentials, which you probably don't want to be world readable.

Should I do a pull request to change everything to 640?

**Comment by mariussturm** [comment]
Thanks for the heads up! Will update the permissions soon!

**Comment by gregkare** [comment]
You're welcome :)

It seems to be a really common problem in cookbooks (or at least the ones we're using, I've just done a quick grep), it's a good thing there isn't clear text credentials in every single file though...

**Comment by mariussturm** [comment]
Fixed in https://github.com/Graylog2/graylog2-cookbook/commit/3071d0043f7eaf0fcb7682a75cb9884aca373a21 will be part of version 1.0.1
