### ISSUE TITLE
Configurable NO_RETRIES in the api_check provider

### ISSUE THREAD

**Issue by andrei-striya** [Graylog2/graylog2-cookbook#15]
It will be good to have configurable NO_RETRIES parameters in the api_check provider because my installation fails every time with timeout during the first run. Currently this parameter is hardcoded:
```ruby
NO_RETRIES = 300 # 5 minutes, waiting a second to retry
```

**Comment by mariussturm** [comment]
I have made this setting configurable: https://github.com/Graylog2/graylog2-cookbook/commit/1a295c0ebc2cf92a480ac5c18ba0d78cfd353fbf
But this will most likely not fix your problem. 5 minutes is already a pretty long time to start up a service.
When you install all Graylog components in one Chef run you will see that the Elasticsearch cookbook will delay the start: https://github.com/elasticsearch/cookbook-elasticsearch/blob/master/recipes/default.rb#L146

So what you really need is a wrapper cookbook for elasticsearch that make sure ES is running before you try to start graylog-server and access the API.

**Comment by andrei-striya** [comment]
Thank you for suggestion, I'll try this.
