### ISSUE TITLE
password_secret in /etc/graylog/server/server.conf 

### ISSUE THREAD

**Issue by nilroy** [Graylog2/graylog2-cookbook#18]
In template file graylog.server.conf.erb following line is putting a quotation (") mark around password_secret

<%= config_option 'password_secret', node.graylog2[:password_secret], enclose: '"' -%>

Its will create problem when migrating users from a different installation of graylog2 (older version). This will hinder to use the same password for the users who are in the older graylog2 installation. It seems graylog is misinterpreting the quotation mark. To avoid this problem the above mentioned line in graylog.server.conf.erb should be changed to

<%= config_option 'password_secret', node.graylog2[:password_secret]-%>

**Comment by mariussturm** [comment]
Fixed in master already. You can now define the enclose through an attribute to not break setups with quotation set, look for the default.graylog2[:password_secret_enclose_char] attribute.

**Comment by nilroy** [comment]
Thanks a lot for your quick respose. Any idea when it is getting published in chef supermarket?

**Comment by mariussturm** [comment]
Just released 1.0.2!
