### ISSUE TITLE
Graylog2 server API returns 403 when creating dashboards/inputs/streams, etc on non-master node

### ISSUE THREAD

**Issue by jgarland79** [Graylog2/graylog2-cookbook#20]
It took me a while to find this problem, but when you attempt to create a dashboard, input, or stream using the rest API you will get back a 403 error telling you to go make that sort of API call to the master node instead. The 403 is not logged because line 58 causes a fault here before it reaches line 59 which would have logged the message.

https://github.com/Graylog2/graylog2-cookbook/blob/master/providers/dashboards.rb#L58-L59

I suggest re-ordering those two lines. The same problem also exists here:
https://github.com/Graylog2/graylog2-cookbook/blob/master/providers/streams.rb#L60-L61

There should also be a check to make sure that we received a 200 OK instead of an error code, and then log the error as an error level log message if we get one.

The other problem is that the cookbook is attempting to make configuration changes to a non-master node(This causes our un-handled 403 error). Maybe a new attribute called graylog2[:rest][:master_uri] should be created, or maybe some sort of check to see if we are the master node and skip all of the rest API configuration stuff if we are not the master node. Maybe something like:

https://github.com/Graylog2/graylog2-cookbook/blob/master/recipes/server.rb#L41

if node.graylog2[:ip_of_master] == node.ipaddress

**Comment by jgarland79** [comment]
The 403 error may only apply to streams and dashboards. I'm not sure about inputs.

**Comment by mariussturm** [comment]
The api support will not be continued in the cookbook, please take a look into the content-pack auto loading functionality. With that you can create inputs, streams, dashboards in a more reliable way.
