### ISSUE TITLE
graylog.conf.erb elasticsearch_max_time_per_index

### ISSUE THREAD

**Issue by perbly** [Graylog2/graylog2-cookbook#21]
There is a "h" too much in the end of this line.

elasticsearch_max_time_per_index = <% if Graylog['rotation_time'] != 0 %><%= Graylog['rotation_time'] %><% else %>1<% end %>h

If i run: sudo graylog-ctl set-retention --time=1d --indices=20 --journal=5
The graylog.conf is set too;
elasticsearch_max_time_per_index = 1dh

And graylog failes to start because of the h.

**Comment by mariussturm** [comment]
When using the `graylog-ctl` command please provide the retention time in h-ours like documented here: https://github.com/Graylog2/graylog2-images/tree/master/ova#configure-message-retention
