### ISSUE TITLE
Support for graylog v1.1.0

### ISSUE THREAD

**Issue by nilroy** [Graylog2/graylog2-cookbook#27]
It might be too early to ask this question. When are you planing to support graylog version 1.1.0?

**Comment by nilroy** [comment]
I am currently setting the major version to 1.1 and server version and web version to 1.1.0-8 and its setup perfectly

node.set[:graylog2][:major_version] = '1.1'
node.set[:graylog2][:server][:version] = '1.1.0-8'
node.set[:graylog2][:web][:version] = '1.1.0-8'

**Comment by mariussturm** [comment]
There will be a new release of the cookbook today or tomorrow supporting 1.1.0, thanks!
