### ISSUE TITLE
Impossible to disable max_size_per_index and max_docs_per_index

### ISSUE THREAD

**Issue by gregkare** [Graylog2/graylog2-cookbook#32]
I tried to switch to time-based index limit, but Chef won't let me override an attribute to nil:

https://gist.github.com/gregkare/01c64453c566b131b31b

That's on Chef 11, I haven't tried if Chef 12 still has the same behaviour

Because the config file is written with `max_size_per_index` and `max_docs_per_index` the `max_time_per_index` is ignored

**Comment by mariussturm** [comment]
Hi Greg,
this is a general bug in Chef 11, you can't override with nil.
Take a look here: https://github.com/chef/chef/issues/1507

In your case it should be enough to change `default.graylog2[:elasticsearch][:rotation_strategy]` and ignore the value of `max_size_per_index`.

**Comment by gregkare** [comment]
Thanks Marius!
