### ISSUE TITLE
User admin_access_token from encrypted databag

### ISSUE THREAD

**Issue by slowjack2k** [Graylog2/graylog2-cookbook#37]
Hi,

is it possible that the `admin_access_token` can also be stored in the encrypted data bag?

regards 
dieter

**Comment by mariussturm** [comment]
Hi,
currently that's not possible, only attributes in node['graylog2'][server|web|radio]* can be set with a databag. But I will keep this open because we have to rework that part of the cookbook anyway.

**Comment by slowjack2k** [comment]
Thanks. The password for mongo db would be also a good choice to place within an encrypted data bag.

**Comment by mariussturm** [comment]
This is possible in v2.0
