### ISSUE TITLE
attribute [:graylog2][:server][:log_file] directory issue

### ISSUE THREAD

**Issue by se-gengo** [Graylog2/graylog2-cookbook#39]
If I try to override attribute [:graylog2][:server][:log_file]  is correctly updates in log4j.xml, however it doesn't create the necessary directory, or ensures that it has correct ownership/permissions.
Can this be handled in this cookbook?
Handling this in wrapper recipe poses a problem that for the first run neither the directory, nor the user will exist.

Ref:
https://github.com/Graylog2/graylog2-cookbook/blob/e9eae6148daaeeeadfcdae9dc0abbf01e957b211/attributes/default.rb#L183

**Comment by mariussturm** [comment]
Fixed in version 1.2.1
