### ISSUE TITLE
kitchen install of graylog2::api_access hangs on faraday-conductivity

### ISSUE THREAD

**Issue by bcorner13** [Graylog2/graylog2-cookbook#44]
Without this feature I have been able to get all of the service to startup on amazon ec2. When enabling this feature however it hangs on the test faraday-conductivity. Any ideas what to look for?  I was thinking something with proxy?

**Comment by mariussturm** [comment]
Hi,
thats possible, faraday-conductivity is a ruby gem. The test suite needs to download and install it in order to run the tests. Without proper internet connection this will fail.
