### ISSUE TITLE
Initial config wrong

### ISSUE THREAD

**Issue by runningman84** [Graylog2/graylog2-cookbook#51]
My wrapper cookbook overwrites specific values like:
```
    default['graylog2']['elasticsearch']['max_size_per_index'] = 1073741824
    default['graylog2']['elasticsearch']['rotation_strategy'] = 'size'
```
But the web interface still shows the wrong settings after the first chef run. I have to restart it manually in order to see the changes.

**Comment by mariussturm** [comment]
Those settings go to the server configuration file and therefore just the server is restarted automatically:
https://github.com/Graylog2/graylog2-cookbook/blob/master/recipes/server.rb#L65

Could you please verify that this happens in your setup? If the web interface is not reflecting the change I guess that is a bug then in the web interface itself.

**Comment by mariussturm** [comment]
With version 2.0 and the merge of the web interface to the server, this should be no problem anymore.
