### ISSUE TITLE
Use of chef-vault for graylog secrets in 2.0

### ISSUE THREAD

**Issue by richardlock** [Graylog2/graylog2-cookbook#52]
With the graylog 1.x cookbook, I was able to use chef-vault to load the various secrets instead of using an encrypted data bag.  With the 2.0 cookbook, it doesn't use "Chef::Mixin::DeepMerge.deep_merge" any more.

This works ok with the attribute assignment for "password_secret" and "root_password_sha2":
https://github.com/Graylog2/graylog2-cookbook/blob/47e013ad5bf56c38c01786bc2ea0afbaf63bc2ab/recipes/server.rb#L7-L8

But not for "rest_tls_key_password" and "web_tls_key_password" because it attempts to use the encrypted data bag item first instead of the attribute.

https://github.com/Graylog2/graylog2-cookbook/blob/47e013ad5bf56c38c01786bc2ea0afbaf63bc2ab/recipes/server.rb#L72-L73

Is it possible to have "rest_tls_key_password" and "web_tls_key_password" function the same way as "password_secret" and "root_password_sha2", or to use some other method to support chef-vault?  The other option would be to use chef-vault instead of encrypted data bags because they seem to be a better solution for storing/retrieving secrets, and can fall back to using unencrypted data bags for use in test-kitchen.

With the current version of the 2.0 cookbook, I can't find a way to converge my wrapper cookbook any more and I would like to test the 2.0.0-2.beta.3 version.

Thanks, Richard

**Comment by richardlock** [comment]
This looks related to issue #55 and the solution proposed there might resolve the issue with using chef-vault also.

**Comment by mariussturm** [comment]
Alright, merged, closing this.
