### ISSUE TITLE
Can't run default, server and api_access cookbooks in one pass

### ISSUE THREAD

**Issue by jrnt30** [Graylog2/graylog2-cookbook#53]
We were looking to provision a "stand alone" Graylog node with a few default inputs setup via Chef with the api_access recipe. In practice we have been unable to provision the "default", "server" and "api_access" recipes in a single Chef pass. 

**Issue:**
The "api_access" recipe is expecting the API endpoints for the Graylog service to be enabled prior to the cookbook running, however the default notification policy on the service is "delayed".  As this has not yet been triggered, the "api_access" recipe will timeout after several minutes of waiting for the endpoint to become available. 

**Expected Behavior:**
Recipes are able to better synergize with one another and be installed in series on a single node in one Chef run. 

**Steps To Reproduce:**
Add the "recipe[api_access]" to the runlist via the .kitchen.yml.  Example log @ http://pastebin.com/raw/K4TT3ze3

**Attempted Resolutions:**
I am still working through this, but I have not come up with a great solution yet.  Things we've tried: 

* Adjusting the graylog2.restart to immediate (this seems to create some contention on the Kafka lock file with all the restarts happening but need to check this again) 
* Adding in an additional "graylog2-server" service declaration via a wrapper cookbook with a start action

**Comment by mariussturm** [comment]
Thanks for the report!
This is exactly the reason why the api_access recipe is not in the kitchen.yml. For the 2.0 version of this cookbook we deleted the recipe completly in favor of content pack auto loading. With newer versions of Graylog you can place a json file somewhere and let Graylog-server load it at start-up time. With this you can create Inputs, Streams, Dashboards... Take a look here: https://github.com/Graylog2/graylog2-server/blob/master/misc/graylog.conf#L393

**Comment by jrnt30** [comment]
Thanks, I will take a look at that.  Is the 2.0 branch in a state where you would say it's safe to start consuming (with some disclaimers around ongoing development obvious ;) )?

**Comment by mariussturm** [comment]
We just updated our own instance to GL 2.0 with it, so it's pretty ok already. But it's possible that there will be changes in the near future in that branch.

**Comment by jrnt30** [comment]
Thanks for the feedback.  I was able to get this working with the new attribute overrides and managing our own JSON file with the inputs setup.  

One thing that could be handy would: 
* Update LWRPs that leveraged the `api_access` cookbook such as `inputs` to instead write out shell content_pack templates to the auto-load folder
* dynamic management of the base `default['graylog2']['server']['content_packs_auto_load']` attribute to aggregate all of the LWRP's templates 

That way, as a user I would simply need to declare what I wanted (inputs, dahsboard, etc.) through Chef and not need to worry about managing the various attributes & JSON templates.
