### ISSUE TITLE
missing the web recipe

### ISSUE THREAD

**Issue by jamiebuxxx** [Graylog2/graylog2-cookbook#57]
Hello,

When building out a test environment to upgrade our graylog2 cluster, I noticed that the web recipe is missing. Is this on purpose?

**Comment by mariussturm** [comment]
Hey,
yes this on purpose, the Graylog web interface moved into the server with version 2.0. So there is no seperate program to install anymore.

**Comment by jamiebuxxx** [comment]
Ok. When deploying a multiple graylog2 server cluster, how does web interface know about the other servers in the cluster. I assume, the server that is set to master will also run web interface. But how are the server backends set now in 2.0.0?

https://github.com/Graylog2/graylog2-cookbook/blob/master/recipes/web.rb#L39

Thanks

**Comment by mariussturm** [comment]
Either the transport_uri is used for connections back to Graylog api: https://github.com/Graylog2/graylog2-cookbook/blob/2.0/attributes/default.rb#L45
Or you can set a HTTP header in your proxy/loadbalancer to tell the web interface how to reach an api endpoint: https://github.com/Graylog2/omnibus-graylog2/blob/2.0/files/graylog-cookbooks/graylog/templates/default/nginx.conf.erb#L26

**Comment by jamiebuxxx** [comment]
Ok, so the `node.graylog2[:rest][:transport_uri]` attribute should be set to the URI of the server handling web request on each additional server node? 

server1:
```
node.graylog2[:web][:enable] = true
node.graylog2[:rest][:transport_uri] = http://server1:12900
```

server2:
```
node.graylog2[:web][:enable] = false
node.graylog2[:rest][:transport_uri] = http://server1:12900
```

Or should the attribute be an array of servers.

server1:
```
node.graylog2[:web][:enable] = true
node.graylog2[:rest][:transport_uri] = http://server1:12900,http://server2:12900
```

server2:
```
node.graylog2[:web][:enable] = false
node.graylog2[:rest][:transport_uri] = http://server1:12900
```

**Comment by mariussturm** [comment]
Use just a single url like in the first example, you can put a loadbalancer infront of all the servers afterwards.

**Comment by jamiebuxxx** [comment]
Ok. And just to be clear, the additional servers would have the `node.graylog2[:rest][:transport_uri] ` attribute set to the rest uri of the master web server?

**Comment by mariussturm** [comment]
The `transport_uri` will be promoted to other servers and web interface instances to know how to connect back to this server, you can read about here: https://github.com/Graylog2/graylog2-server/blob/master/misc/graylog.conf#L46
Depends on how your setup looks like you can set it to a public IP or 0.0.0.0 if all interfaces are used by Graylog.
