### ISSUE TITLE
Old version of Collector on Ubuntu

### ISSUE THREAD

**Issue by danielkleinert** [Graylog2/graylog2-cookbook#64]
The collector recipe installs version 0.4.2 instead of 0.5.0 on Ubuntu 14.04 which isn't compatible with Graylog 2.0.

**Comment by mariussturm** [comment]
Please update to the latest version of this cookbook, it's set to 0.5.0 there: https://github.com/Graylog2/graylog2-cookbook/blob/master/attributes/default.rb#L8

**Comment by danielkleinert** [comment]
I am already using the newest version of the cookbooks. 

To me it looks like the recipe is not taking the attribute you mention into account on Debian 8, Ubuntu 14.04 / 12.04 as well as CentOS 7.

It seams that for these specific Platforms the newest version from the repository is installed which happens to be 0.4.2. At least that is what happened in Ubuntu 14.04 i think.

**Comment by mariussturm** [comment]
Should be fixed in 2.0.5
