### ISSUE TITLE
log4j2 appender STDOUT results in undesirable output when (re)starting service

### ISSUE THREAD

**Issue by coffee-squirrel** [Graylog2/graylog2-cookbook#66]
## Expected Behavior

Restarting the `graylog-server` service should not result in Graylog Server output appearing on STDOUT.

Ideally `graylog2-cookbook/templates/default/graylog.server.log4j2.xml.erb` would be made consistent with `fpm-recipes/recipes/graylog-server/files/log4j2.xml`, which (among other things) does not have a STDOUT appender.

## Current Behavior

Restarting the `graylog-server` service (without doing output redirection) results in Graylog Server output appearing directly in the console.

## Possible Solution

Removal of the STDOUT appender in `graylog2-cookbook/templates/default/graylog.server.log4j2.xml.erb`, removal of the STDOUT appender from the Root logger, or an attribute controlling whether STDOUT is included (but disabled by default).

## Steps to Reproduce (for bugs)

1. Install Graylog Server using version 2.0.5 of the Graylog2 cookbook
2. Restart the Graylog Server service (`sudo service graylog-server restart`)
3. Note Graylog Server output appears in the console
4. Reconnect to the server/VM
5. Edit `graylog2-cookbook/templates/default/graylog.server.log4j2.xml.erb`, removing `<AppenderRef ref="STDOUT"/>` from the Root logger.
6. Restart the Graylog Server service (`sudo service graylog-server restart`)
6. Note Graylog Server output no longer appears in the console

## Your Environment
* Graylog Cookbook Version: 2.0.5
* Graylog Version: 2.0.3
* Elasticsearch Version:  2.2.0
* MongoDB Version:  2.6.12
* Operating System:  Red Hat Enterprise Linux Server release 6.7
* Browser version:  Firefox 48

**Comment by mariussturm** [comment]
Thanks for the report, should be fixed with https://github.com/Graylog2/graylog2-cookbook/commit/28525f07d5a072798fd1ef9c1df6e36edd3ab42a

**Comment by coffee-squirrel** [comment]
Thank you!
