### ISSUE TITLE
Allow to configure trusted proxies

### ISSUE THREAD

**Issue by runningman84** [Graylog2/graylog2-cookbook#70]
nt

**Comment by mariussturm** [comment]
? what is a trusted proxy for you  and in which context? Web interface, Rest API?? What is the scenario and use case?

**Comment by runningman84** [comment]
I would like to configure trusted proxies for the sso plugin and I would also like to configure the sso plugin itself using this cookbook

**Comment by mariussturm** [comment]
Please use the attribute `[:server][:additional_options]` for plugin configurations. Everything that goes in there will be appended to the server config. We can't provide cookbook support for plugins, that would not be maintainable.
