### ISSUE TITLE
additional options attribute should be a Hash

### ISSUE THREAD

**Issue by runningman84** [Graylog2/graylog2-cookbook#71]
I would like to setup options like this:

default['graylog2']['server']['additional_options']['trusted_proxies'] = '127.0.0.1/32, 0:0:0:0:0:0:0:1/128'
default['graylog2']['server']['additional_options']['whatever'] = false

But the additional_options only supports a string which does not allow mutiple options...

**Comment by mariussturm** [comment]
The `trusted_proxies` attribute is a core setting and was just added to the cookbook, update to v2.1.3.
You can use a multi line string for the `additional_options` attribute if you want to set more then one setting. Switching this to a hash would break all running installations which make use of it.
