### ISSUE TITLE
Elasticsearch cluster name not set

### ISSUE THREAD

**Issue by brucebolden** [Graylog2/graylog2-cookbook#72]
I have created a role in chef using the recommended attributes from the graylog cookbook README file.

`"elasticsearch": {
      "version": "2.2.0",
      "cluster": {
        "name": "graylog"
      }
    },
`
For some reason Elasticsearch is not taking the cluster name from my role attribute.  The /etc/elasticsearch/elasticsearch.yml continues to use the default "elasticsearch" cluster name.

**Comment by mariussturm** [comment]
Without further informations I can help much. How does the role looks like, which version of the elasticsearch cookbook do you use? Did you make sure that you didn't put Elasticsearch configurations under the graylog2_ attribute name space? Did you compared your role to with this: https://github.com/Graylog2/graylog2-cookbook/blob/master/.kitchen.yml#L96 ?

**Comment by brucebolden** [comment]
I am using the elasticsearch from supermarket (2.32)
In my configuration, I am not using vagrant.
The following is my role.
`{
  "name": "graylog",
  "description": "",
  "json_class": "Chef::Role",
  "default_attributes": {
    "java": {
      "jdk_version": "8",
      "install_flavor": "openjdk"
    },
    "mongodb": {
      "package_name": "mongodb-org-server"
    },
    "elasticsearch": {
      "version": "2.2.0",
      "cluster": {
        "name": "graylog"
      }
    },
    "graylog2": {
      "password_secret": "ZxUahiN48EFVJgzRTzGO2olFRmjmsvzybSf4YwBvn5x1asLUBPe8GHbOQTZ0jzuAB7dzrNPk3wCEH57PCZm23MHAET0G653G",
      "root_password_sha2": "acfe6cb79c596ebe8503asddfsewww2c4855b3b22b081cdcca0baa7b92527749b4e",
      "server": {
        "java_opts": "-Djava.net.preferIPv4Stack=true"
      }
    }
  },
  "override_attributes": {
    "elasticsearch": {
      "version": "2.2.0",
      "cluster": {
        "name": "graylog"
      }
    }
  },
  "chef_type": "role",
  "run_list": [
    "recipe[java]",
    "recipe[elasticsearch]",
    "recipe[mongodb]",
    "recipe[graylog2]",
    "recipe[graylog2::server]"
  ],
  "env_run_lists": {

  }
}
~
`

**Comment by mariussturm** [comment]
The exact same version works for me, so I guess it's not a bug in the graylog2 or elasticsearch cookbook. The clustername is so fundamental that a failure would cause a lot more noise. Sorry but without digging into your system there is not much I can do.

**Comment by brucebolden** [comment]
Thanks Mariussturm  for looking into this.  I was able to get the graylog2 cookbook working by using the elasticsearch-cluster cookbook on supermarket.

**Comment by starkj** [comment]
Hi there, same here. chef-client keeps creating this line `cluster.name: elasticsearch` in my `/etc/elasticsearch/elasticsearch.yml` with this configuration:
```javascript
{
  "name": "graylogserver",
  "chef_environment": "_default",
  "run_list": [
  "recipe[java]",
  "recipe[elasticsearch]",
  "recipe[mongodb]",
  "recipe[graylog2]",
  "recipe[graylog2::server]"
]
,
  "normal": {
    "tags": [

    ],
    "java": {
      "jdk_version": "8",
      "install_flavor": "oracle",
      "oracle": {
        "accept_oracle_download_terms": true
      }
    },
    "elasticsearch": {
      "version": "2.2.0",
      "cluster": {
        "name": "graylog"
      }
    },
    "graylog2": {`
[...]
```

After having a closer look at https://github.com/elastic/cookbook-elasticsearch I cannot find any support for an attribute like `elasticsearch.cluster`. Or is there some chef attribut magic going on I'm not aware of?
The docs for elasticsearch cookbook say you should provide an attribute called `configuration` when using the provider `elasticsearch_configure` to set a custom clustername.

Looking at an older version of the elasticsearch cookbook (https://github.com/elastic/cookbook-elasticsearch/tree/v0.3.14) they supported an `elasticsearch.cluster` attribute back then. But I think now support is gone.

I'm using this cookbook versions:
- elasticsearch: 2.3.0
- graylog2: 2.1.4

So I guess to fix this one need to run the elasticsearch provides in a custom recipe?

**Comment by mariussturm** [comment]
@starkj the Elasticsearch cookbook is a pure resource cookbook (at least in a half way current version) you always need another cookbook that calls the resources. The Graylog cookbook only takes care of the installation of Graylog itself, it's not doing anything with Elasticsearch. To run the integration tests we have this wrapper recipe to setup and configure Elasticsearch: https://github.com/Graylog2/graylog2-cookbook/blob/master/test/fixtures/cookbooks/elasticsearch_test/recipes/default.rb

This is all documented in the README of the ES cookbook: https://github.com/elastic/cookbook-elasticsearch#recipes

**Comment by starkj** [comment]
Thx @mariussturm for your fast reply and sry for my late answer (been really busy lately)

You’re absolutely right that the Elasticsearch cookbook is supposed to be used just as a pure resource cookbook. Thanks for the hint!

Despite this the cookbook does have a default recipe which creates an Elasticsearch cluster named `elasticsearch` and it is executed if you’ve got a runlist like this (taken for the README):
```
run_list "recipe[java]",
         "recipe[elasticsearch]",
         "recipe[mongodb]",
         "recipe[graylog2]",
         "recipe[graylog2::server]”

```
In addition the README of the Graylog2 cookbook makes a suggestion, to configure the Elasticsearch cluster name like this, which actually does not work:
```
"elasticsearch": {
    "version": "2.2.0",
    "cluster": {
        "name": "graylog"
    }
}
```
So that got me confused a litte and maybe was the problem of @brucebolden, too.

So would you appreciate a pull request for updating the README here? I’d be happy to prepare one!

**Comment by mariussturm** [comment]
@starkj true, that snippet is from an outdated elasticsearch cookbook version. Feel free to contribute!
