### ISSUE TITLE
Support ubuntu 16.04 ?

### ISSUE THREAD

**Issue by aileo** [Graylog2/graylog2-cookbook#76]
Hello,

Graylog install fails on Ubuntu 16.04 as the `tzdata-java` package is no longer in repositories, [according to this page](http://askubuntu.com/questions/795901/what-happened-to-tzdata-java-in-xenial-16-04).

Is it planned to support Ubuntu 16.04 at some point or should I definitly use 14.04 for my graylog server ?

**Comment by mariussturm** [comment]
Hi,
the Graylog packages should work on 16.04 but we simply hadn't the time yet to port the cookbook. So if you want to use the cookbook I would stick with 14.04 at the moment.

**Comment by joschi** [comment]
@aileo Of course pull requests to make this cookbook work with Ubuntu 16.04 are welcome. 😄

**Comment by aileo** [comment]
After several code reading i found out there was a work around to make it work (at least install) with Ubuntu 16.40, by setting node attribute :

```json
{
  "graylog2" : {
    "server": {
      "install_tzdata_java": false
    }
  }
}
```

I will consider making PR to turn false this attrubute by default on Ubuntu 16.04 but I don't think it worse it.

**Comment by mariussturm** [comment]
Once it's tested properly with 16.04 we can put that in the README, thanks!
