### ISSUE TITLE
Elasticsearch cookbook 3.x.x not compatible

### ISSUE THREAD

**Issue by donwlewis** [Graylog2/graylog2-cookbook#83]
It seems that the elasticsearch cookbook 3.x.x and great only supports installation of version 5.x and above of elasticsearch.  Dependencies need to be changed in order to reflect this.

**Comment by mariussturm** [comment]
We don't have a hard dependency on the ES cookbook but I have pointed it out here: https://github.com/Graylog2/graylog2-cookbook/commit/62dd81a024e2f27fd89691c1eb5ec27ad0f1a9aa
