### ISSUE TITLE
Incorrect URL to package repos

### ISSUE THREAD

**Issue by tpbowden** [Graylog2/graylog2-cookbook#84]
In `recipes/default.rb` the yum repo is set to be located at `https://packages.graylog2.org/repo/el/stable/...` which doesn't appear to be valid.

I'm not sure whether this is an issue with the cookbook or with the repo itself however.

**Comment by tpbowden** [comment]
Seems to be a repo issue

**Comment by joschi** [comment]
@tpbowden Why do you think the URL is not valid?

**Comment by tpbowden** [comment]
Because if you follow it you get 404s, but that is because only direct links to packages work and then redirect to S3
