### ISSUE TITLE
Graylog meta package is downloaded after disabling it

### ISSUE THREAD

**Issue by n002213f** [Graylog2/graylog2-cookbook#85]
The cookbook allows the use of a custom repo to download graylog packages. Line 7 & 8 in the [attributes/default.rb](https://github.com/Graylog2/graylog2-cookbook/blob/master/attributes/default.rb#L7) file says, `By default the cookbook installs a meta package containing the key and URL for the current Graylog repository. To disable this behavior set your own repository informations here.`

However even after specifying the custom repos, the default cookbook download the same package, [recipes/default.rb](https://github.com/Graylog2/graylog2-cookbook/blob/master/recipes/default.rb#L13) on line 13

Downloading of the file should be moved to between line 30 & 31 in [recipes/default.rb](https://github.com/Graylog2/graylog2-cookbook/blob/master/recipes/default.rb#L30-L31) where the file is required.

**Comment by mariussturm** [comment]
Thanks for the report!
Fixed in 2.2.3 https://github.com/Graylog2/graylog2-cookbook/commit/eb6ad8ffbed6518e51e172a00296b66cc9e32bf9
