### ISSUE TITLE
Can't upgrade to 2.2 from 2.0.3 in CentOS

### ISSUE THREAD

**Issue by tharu8** [Graylog2/graylog2-cookbook#86]
When I tried below command it display error as "curl: (6) Couldn't resolve host 'packages.graylog2.org'"

 rpm -Uvh https://packages.graylog2.org/repo/packages/graylog-2.1-repository_latest.rpm
Retrieving https://packages.graylog2.org/repo/packages/graylog-2.1-repository_latest.rpm
curl: (6) Couldn't resolve host 'packages.graylog2.org'
error: skipping https://packages.graylog2.org/repo/packages/graylog-2.1-repository_latest.rpm - transfer failed

I have manually added repository in /etc/yum.repos.d/graylog.repo

But same error message observed

**Comment by n002213f** [comment]
Can you ping `packages.graylog2.org`? Your server is failing connect to the specified server.

**Comment by tharu8** [comment]
@n002213f No, ping is failing to packages.graylog2.org

I go through internet using a user proxy and I have configure proxy settings in /etc/yum.conf

So do I have to configure any other configuration file ?

**Comment by joschi** [comment]
@tharu8 This looks like a problem in your network setup, not a problem with Graylog or its package repositories.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
