### ISSUE TITLE
Remove "recommends" from metadata.rb

### ISSUE THREAD

**Issue by astral303** [Graylog2/graylog2-cookbook#90]
Could you please remove "recommends" sections or change "recommends" to "suggests"?

The official MongoDB Chef cookbook has been de-facto abandoned and so I've built a recipe that deploys Mongo using sc-mongodb (from sous-chefs). See the deprecation notice for "mongodb" here: https://supermarket.chef.io/cookbooks/mongodb

But unfortunately, because of the "recommends" statements, Berkshelf treats them as required dependencies: https://github.com/berkshelf/berkshelf/issues/895 and https://github.com/chef/chef-rfc/pull/245 --- this means that the MongoDB cookbook is required to be installed and uploaded by Berks.

Since your cookbook merely needs ANY MongoDB server, no matter which cookbook installs it, and does not actually actively install it itself, I recommend removing these recommends lines, or at least changing to "suggests" (which is also deprecated, but doesn't confuse Berkshelf upload).

**Comment by mariussturm** [comment]
Thanks for the feedback!
This is fixed in 2.2.5
