### ISSUE TITLE
2.2.3 release tag references 2.2.2 package version

### ISSUE THREAD

**Issue by astral303** [Graylog2/graylog2-cookbook#91]
If you attempt to use graylog2 cookbook through the official supermarket means, and reference version 2.2.3, the resultant cookbook at tag 2.2.3 still references Graylog 2.2.2.

**Comment by mariussturm** [comment]
The cookbook version is not always in sync with the latest Graylog release. We try to keep up with the major and minor version number but not the patch level. Please take a look at the attributes.rb file to check which version is deployed. Thanks!
