### ISSUE TITLE
Amazon Linux + Chef 13 = unsupported

### ISSUE THREAD

**Issue by eric-tucker** [Graylog2/graylog2-cookbook#95]
https://github.com/chef/ohai/pull/971

So the repository URL isn't being determined correctly in the default recipe.

**Comment by mariussturm** [comment]
I have added `amazon` to the default recipe: https://github.com/Graylog2/graylog2-cookbook/commit/9b37a1ad7c6ad0a39807cb4204c9818ff4104ade
But keep in mind that it's handled exactly like `rhel`, so when they diverge problems can come up.

**Comment by eric-tucker** [comment]
Thanks!
