### ISSUE TITLE
No easy way to configure Elasticsearch max index size and max number of indices?

### ISSUE THREAD

**Issue by et304383** [Graylog2/graylog2-cookbook#96]
I don't see any attributes exposed for these values, and the "additional_options" attribute I'm not sure what I'm supposed to put in there unless I'm quite literally supposed to put in a new line separated string of values:

```
      "server": {
        "additional_options": "elasticsearch_max_number_of_indices = 14\nelasticsearch_max_size_per_index = 5368709120\nrotation_strategy = size"
      },
```

**Comment by joschi** [comment]
@et304383 The index configuration (or rather index set configuration) has been moved into the database (MongoDB) as of Graylog 2.2.0, see https://www.graylog.org/blog/88-announcing-graylog-v2-2-0.

**Comment by et304383** [comment]
Ahh.  Thanks!
