### ISSUE TITLE
I want write a LWRP

### ISSUE THREAD

**Issue by postgred** [Graylog2/graylog2-cookbook#99]
Dear maintainer, I'm writing a ruby gem for working with Graylog REST API and I want to use the gem for writing custom resources. 

Should I create a new cookbook with LWRP or send PR to this repo? 

Can you review the gem and give me some feedback about code/features/etc.? 

The gem: https://github.com/postgred/graylogapi

**Comment by mariussturm** [comment]
Hi,
feel free to create a PR for this cookbook. I can review it then.

**Comment by postgred** [comment]
Cool! What Chef version are you supporting? I want to use **gem** in the **metadata.rb**, but it works only with chef >= 12.8.

**Comment by mariussturm** [comment]
The tests are running with 12.8.1: https://github.com/Graylog2/graylog2-cookbook/blob/master/.kitchen.yml#L25
But there can be users with old installations, so best thing is to be a little bit conservative with new features. E.g. the Docker cookbook is doing it like this: https://github.com/chef-cookbooks/docker/blob/46501c504ff8e3e86f2bca724061866629bc3e8e/libraries/_autoload.rb#L2
